[package]
name = "three-way-merge-finder"
version = "0.1.0"
authors = ["Ward Muylaert <ward.muylaert@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.10"
clap = "2"
